substitutions:
  name: "outside-shutter"
  friendly_name: "Outside Shutter Controller"

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome

logger:
  baud_rate: 115200 # Enabled for debugging via USB
  # UART0 is used for logging, UART2 (16/17) for communication

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

# SPI Bus for RC522
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# Global PIN Buffer
globals:
  - id: pin_buffer
    type: std::string
    initial_value: '""'

# RC522 Component
rc522_spi:
  cs_pin: GPIO5
  reset_pin: GPIO22 # Optional but recommended
  on_tag:
    then:
      - logger.log:
          format: "RFID Tag Detected: %s"
          args: [ 'x.c_str()' ]
      - lambda: |-
          id(uart_bus).write_str("TAG:");
          id(uart_bus).write_str(x.c_str());
          id(uart_bus).write_str("\n");

# Matrix Keypad
matrix_keypad:
  id: my_keypad
  rows:
    - pin: GPIO32
    - pin: GPIO33
    - pin: GPIO25
    - pin: GPIO26
  columns:
    - pin: GPIO27
    - pin: GPIO14
    - pin: GPIO4
    - pin: GPIO13
  keys: "123A456B789C*0#D"
  on_key:
    then:
      - logger.log:
          format: "Key Pressed: %c"
          args: [ 'x' ]
      - lambda: |-
          if (x >= '0' && x <= '9') {
            id(pin_buffer) += x;
            ESP_LOGD("keypad", "Buffer: %s", id(pin_buffer).c_str());
          } else if (x == '*') {
            id(pin_buffer) = "";
            ESP_LOGD("keypad", "Buffer Cleared");
          } else if (x == '#') {
            id(uart_bus).write_str("PIN:");
            id(uart_bus).write_str(id(pin_buffer).c_str());
            id(uart_bus).write_str("\n");
            id(pin_buffer) = "";
            ESP_LOGD("keypad", "Sent PIN");
          } else if (x == 'A') {
            id(uart_bus).write_str("CMD:UP\n");
          } else if (x == 'B') {
            id(uart_bus).write_str("CMD:DOWN\n");
          } else if (x == 'C') {
            id(uart_bus).write_str("CMD:STOP\n");
          }
